apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 939992775538.dkr.ecr.ap-northeast-2.amazonaws.com/hearus-front-vue
  newName: 939992775538.dkr.ecr.ap-northeast-2.amazonaws.com/hearus-front-vue
  newTag: 709895d0
resources:
- ../../base
patchesStrategicMerge:
- Vue-Deployment-patch.yaml
- Vue-Service-patch.yaml
