apiVersion: v1
kind: Service
metadata:
  name: hearus-front-svc
  labels:
    app.kubernetes.io/name: hearus-front
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 443
      name: hearus-front
  selector:
    app.kubernetes.io/name: hearus-front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hearus-front
  labels:
    app.kubernetes.io/name: hearus-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: hearus-front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hearus-front
    spec:
      containers:
      - image: 939992775538.dkr.ecr.ap-northeast-2.amazonaws.com/hearus-front-vue:1d2d1f92
        name: hearus-front
        env:
        - name: VUE_APP_K8S
          value: https://k8s-default-hearusin-9dcb9ae515-1957827347.ap-northeast-2.elb.amazonaws.com
        ports:
        - containerPort: 443
          name: hearus-front